// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api_test

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/willie68/schematic2/backend/internal/domain"
)

// newMockdocumentStore creates a new instance of mockdocumentStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdocumentStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdocumentStore {
	mock := &mockdocumentStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdocumentStore is an autogenerated mock type for the documentStore type
type mockdocumentStore struct {
	mock.Mock
}

type mockdocumentStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdocumentStore) EXPECT() *mockdocumentStore_Expecter {
	return &mockdocumentStore_Expecter{mock: &_m.Mock}
}

// ListTags provides a mock function for the type mockdocumentStore
func (_mock *mockdocumentStore) ListTags(ctx context.Context) ([]domain.Tag, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTags")
	}

	var r0 []domain.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Tag, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Tag); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockdocumentStore_ListTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTags'
type mockdocumentStore_ListTags_Call struct {
	*mock.Call
}

// ListTags is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockdocumentStore_Expecter) ListTags(ctx interface{}) *mockdocumentStore_ListTags_Call {
	return &mockdocumentStore_ListTags_Call{Call: _e.mock.On("ListTags", ctx)}
}

func (_c *mockdocumentStore_ListTags_Call) Run(run func(ctx context.Context)) *mockdocumentStore_ListTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockdocumentStore_ListTags_Call) Return(tags []domain.Tag, err error) *mockdocumentStore_ListTags_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *mockdocumentStore_ListTags_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Tag, error)) *mockdocumentStore_ListTags_Call {
	_c.Call.Return(run)
	return _c
}

// SuggestTags provides a mock function for the type mockdocumentStore
func (_mock *mockdocumentStore) SuggestTags(ctx context.Context, prefix string, limit int) ([]domain.Tag, error) {
	ret := _mock.Called(ctx, prefix, limit)

	if len(ret) == 0 {
		panic("no return value specified for SuggestTags")
	}

	var r0 []domain.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) ([]domain.Tag, error)); ok {
		return returnFunc(ctx, prefix, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) []domain.Tag); ok {
		r0 = returnFunc(ctx, prefix, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, prefix, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockdocumentStore_SuggestTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SuggestTags'
type mockdocumentStore_SuggestTags_Call struct {
	*mock.Call
}

// SuggestTags is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
//   - limit int
func (_e *mockdocumentStore_Expecter) SuggestTags(ctx interface{}, prefix interface{}, limit interface{}) *mockdocumentStore_SuggestTags_Call {
	return &mockdocumentStore_SuggestTags_Call{Call: _e.mock.On("SuggestTags", ctx, prefix, limit)}
}

func (_c *mockdocumentStore_SuggestTags_Call) Run(run func(ctx context.Context, prefix string, limit int)) *mockdocumentStore_SuggestTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockdocumentStore_SuggestTags_Call) Return(tags []domain.Tag, err error) *mockdocumentStore_SuggestTags_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *mockdocumentStore_SuggestTags_Call) RunAndReturn(run func(ctx context.Context, prefix string, limit int) ([]domain.Tag, error)) *mockdocumentStore_SuggestTags_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type mockdocumentStore
func (_mock *mockdocumentStore) Upsert(doc domain.Document) error {
	ret := _mock.Called(doc)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(domain.Document) error); ok {
		r0 = returnFunc(doc)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockdocumentStore_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type mockdocumentStore_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - doc domain.Document
func (_e *mockdocumentStore_Expecter) Upsert(doc interface{}) *mockdocumentStore_Upsert_Call {
	return &mockdocumentStore_Upsert_Call{Call: _e.mock.On("Upsert", doc)}
}

func (_c *mockdocumentStore_Upsert_Call) Run(run func(doc domain.Document)) *mockdocumentStore_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Document
		if args[0] != nil {
			arg0 = args[0].(domain.Document)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockdocumentStore_Upsert_Call) Return(err error) *mockdocumentStore_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockdocumentStore_Upsert_Call) RunAndReturn(run func(doc domain.Document) error) *mockdocumentStore_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// newMockdocumentIndex creates a new instance of mockdocumentIndex. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdocumentIndex(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdocumentIndex {
	mock := &mockdocumentIndex{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdocumentIndex is an autogenerated mock type for the documentIndex type
type mockdocumentIndex struct {
	mock.Mock
}

type mockdocumentIndex_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdocumentIndex) EXPECT() *mockdocumentIndex_Expecter {
	return &mockdocumentIndex_Expecter{mock: &_m.Mock}
}

// Search provides a mock function for the type mockdocumentIndex
func (_mock *mockdocumentIndex) Search(query string, tags []string) []domain.SearchResult {
	ret := _mock.Called(query, tags)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []domain.SearchResult
	if returnFunc, ok := ret.Get(0).(func(string, []string) []domain.SearchResult); ok {
		r0 = returnFunc(query, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SearchResult)
		}
	}
	return r0
}

// mockdocumentIndex_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type mockdocumentIndex_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - query string
//   - tags []string
func (_e *mockdocumentIndex_Expecter) Search(query interface{}, tags interface{}) *mockdocumentIndex_Search_Call {
	return &mockdocumentIndex_Search_Call{Call: _e.mock.On("Search", query, tags)}
}

func (_c *mockdocumentIndex_Search_Call) Run(run func(query string, tags []string)) *mockdocumentIndex_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockdocumentIndex_Search_Call) Return(searchResults []domain.SearchResult) *mockdocumentIndex_Search_Call {
	_c.Call.Return(searchResults)
	return _c
}

func (_c *mockdocumentIndex_Search_Call) RunAndReturn(run func(query string, tags []string) []domain.SearchResult) *mockdocumentIndex_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type mockdocumentIndex
func (_mock *mockdocumentIndex) Upsert(doc domain.Document) {
	_mock.Called(doc)
	return
}

// mockdocumentIndex_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type mockdocumentIndex_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - doc domain.Document
func (_e *mockdocumentIndex_Expecter) Upsert(doc interface{}) *mockdocumentIndex_Upsert_Call {
	return &mockdocumentIndex_Upsert_Call{Call: _e.mock.On("Upsert", doc)}
}

func (_c *mockdocumentIndex_Upsert_Call) Run(run func(doc domain.Document)) *mockdocumentIndex_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Document
		if args[0] != nil {
			arg0 = args[0].(domain.Document)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockdocumentIndex_Upsert_Call) Return() *mockdocumentIndex_Upsert_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockdocumentIndex_Upsert_Call) RunAndReturn(run func(doc domain.Document)) *mockdocumentIndex_Upsert_Call {
	_c.Run(run)
	return _c
}

// newMockblobStore creates a new instance of mockblobStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockblobStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockblobStore {
	mock := &mockblobStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockblobStore is an autogenerated mock type for the blobStore type
type mockblobStore struct {
	mock.Mock
}

type mockblobStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockblobStore) EXPECT() *mockblobStore_Expecter {
	return &mockblobStore_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type mockblobStore
func (_mock *mockblobStore) Save(data []byte, mimeType string) (*domain.ContainerInfo, error) {
	ret := _mock.Called(data, mimeType)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *domain.ContainerInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, string) (*domain.ContainerInfo, error)); ok {
		return returnFunc(data, mimeType)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, string) *domain.ContainerInfo); ok {
		r0 = returnFunc(data, mimeType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ContainerInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, string) error); ok {
		r1 = returnFunc(data, mimeType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockblobStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type mockblobStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - data []byte
//   - mimeType string
func (_e *mockblobStore_Expecter) Save(data interface{}, mimeType interface{}) *mockblobStore_Save_Call {
	return &mockblobStore_Save_Call{Call: _e.mock.On("Save", data, mimeType)}
}

func (_c *mockblobStore_Save_Call) Run(run func(data []byte, mimeType string)) *mockblobStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockblobStore_Save_Call) Return(containerInfo *domain.ContainerInfo, err error) *mockblobStore_Save_Call {
	_c.Call.Return(containerInfo, err)
	return _c
}

func (_c *mockblobStore_Save_Call) RunAndReturn(run func(data []byte, mimeType string) (*domain.ContainerInfo, error)) *mockblobStore_Save_Call {
	_c.Call.Return(run)
	return _c
}
