// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/willie68/gowillie68/pkg/measurement"
	"github.com/willie68/schematics2/backend/internal/domain/model"
	"github.com/willie68/schematics2/backend/internal/services/users"
)

// newMockdocumentStore creates a new instance of mockdocumentStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdocumentStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdocumentStore {
	mock := &mockdocumentStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdocumentStore is an autogenerated mock type for the documentStore type
type mockdocumentStore struct {
	mock.Mock
}

type mockdocumentStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdocumentStore) EXPECT() *mockdocumentStore_Expecter {
	return &mockdocumentStore_Expecter{mock: &_m.Mock}
}

// CountAll provides a mock function for the type mockdocumentStore
func (_mock *mockdocumentStore) CountAll(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountAll")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockdocumentStore_CountAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountAll'
type mockdocumentStore_CountAll_Call struct {
	*mock.Call
}

// CountAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockdocumentStore_Expecter) CountAll(ctx any) *mockdocumentStore_CountAll_Call {
	return &mockdocumentStore_CountAll_Call{Call: _e.mock.On("CountAll", ctx)}
}

func (_c *mockdocumentStore_CountAll_Call) Run(run func(ctx context.Context)) *mockdocumentStore_CountAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockdocumentStore_CountAll_Call) Return(n int64, err error) *mockdocumentStore_CountAll_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *mockdocumentStore_CountAll_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *mockdocumentStore_CountAll_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type mockdocumentStore
func (_mock *mockdocumentStore) DeleteByID(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockdocumentStore_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type mockdocumentStore_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *mockdocumentStore_Expecter) DeleteByID(ctx any, id any) *mockdocumentStore_DeleteByID_Call {
	return &mockdocumentStore_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id)}
}

func (_c *mockdocumentStore_DeleteByID_Call) Run(run func(ctx context.Context, id string)) *mockdocumentStore_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockdocumentStore_DeleteByID_Call) Return(err error) *mockdocumentStore_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockdocumentStore_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, id string) error) *mockdocumentStore_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type mockdocumentStore
func (_mock *mockdocumentStore) GetByID(ctx context.Context, id string) (model.Document, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.Document
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Document, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Document); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Document)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockdocumentStore_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type mockdocumentStore_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *mockdocumentStore_Expecter) GetByID(ctx any, id any) *mockdocumentStore_GetByID_Call {
	return &mockdocumentStore_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *mockdocumentStore_GetByID_Call) Run(run func(ctx context.Context, id string)) *mockdocumentStore_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockdocumentStore_GetByID_Call) Return(document model.Document, err error) *mockdocumentStore_GetByID_Call {
	_c.Call.Return(document, err)
	return _c
}

func (_c *mockdocumentStore_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (model.Document, error)) *mockdocumentStore_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// HasHash provides a mock function for the type mockdocumentStore
func (_mock *mockdocumentStore) HasHash(ctx context.Context, hash string) bool {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for HasHash")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// mockdocumentStore_HasHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasHash'
type mockdocumentStore_HasHash_Call struct {
	*mock.Call
}

// HasHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *mockdocumentStore_Expecter) HasHash(ctx any, hash any) *mockdocumentStore_HasHash_Call {
	return &mockdocumentStore_HasHash_Call{Call: _e.mock.On("HasHash", ctx, hash)}
}

func (_c *mockdocumentStore_HasHash_Call) Run(run func(ctx context.Context, hash string)) *mockdocumentStore_HasHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockdocumentStore_HasHash_Call) Return(b bool) *mockdocumentStore_HasHash_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *mockdocumentStore_HasHash_Call) RunAndReturn(run func(ctx context.Context, hash string) bool) *mockdocumentStore_HasHash_Call {
	_c.Call.Return(run)
	return _c
}

// HasID provides a mock function for the type mockdocumentStore
func (_mock *mockdocumentStore) HasID(ctx context.Context, id string) bool {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for HasID")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// mockdocumentStore_HasID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasID'
type mockdocumentStore_HasID_Call struct {
	*mock.Call
}

// HasID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *mockdocumentStore_Expecter) HasID(ctx any, id any) *mockdocumentStore_HasID_Call {
	return &mockdocumentStore_HasID_Call{Call: _e.mock.On("HasID", ctx, id)}
}

func (_c *mockdocumentStore_HasID_Call) Run(run func(ctx context.Context, id string)) *mockdocumentStore_HasID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockdocumentStore_HasID_Call) Return(b bool) *mockdocumentStore_HasID_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *mockdocumentStore_HasID_Call) RunAndReturn(run func(ctx context.Context, id string) bool) *mockdocumentStore_HasID_Call {
	_c.Call.Return(run)
	return _c
}

// ListTags provides a mock function for the type mockdocumentStore
func (_mock *mockdocumentStore) ListTags(ctx context.Context) ([]model.Tag, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTags")
	}

	var r0 []model.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Tag, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Tag); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockdocumentStore_ListTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTags'
type mockdocumentStore_ListTags_Call struct {
	*mock.Call
}

// ListTags is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockdocumentStore_Expecter) ListTags(ctx any) *mockdocumentStore_ListTags_Call {
	return &mockdocumentStore_ListTags_Call{Call: _e.mock.On("ListTags", ctx)}
}

func (_c *mockdocumentStore_ListTags_Call) Run(run func(ctx context.Context)) *mockdocumentStore_ListTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockdocumentStore_ListTags_Call) Return(tags []model.Tag, err error) *mockdocumentStore_ListTags_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *mockdocumentStore_ListTags_Call) RunAndReturn(run func(ctx context.Context) ([]model.Tag, error)) *mockdocumentStore_ListTags_Call {
	_c.Call.Return(run)
	return _c
}

// SuggestManufacturers provides a mock function for the type mockdocumentStore
func (_mock *mockdocumentStore) SuggestManufacturers(ctx context.Context, prefix string, limit int) ([]string, error) {
	ret := _mock.Called(ctx, prefix, limit)

	if len(ret) == 0 {
		panic("no return value specified for SuggestManufacturers")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) ([]string, error)); ok {
		return returnFunc(ctx, prefix, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) []string); ok {
		r0 = returnFunc(ctx, prefix, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, prefix, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockdocumentStore_SuggestManufacturers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SuggestManufacturers'
type mockdocumentStore_SuggestManufacturers_Call struct {
	*mock.Call
}

// SuggestManufacturers is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
//   - limit int
func (_e *mockdocumentStore_Expecter) SuggestManufacturers(ctx any, prefix any, limit any) *mockdocumentStore_SuggestManufacturers_Call {
	return &mockdocumentStore_SuggestManufacturers_Call{Call: _e.mock.On("SuggestManufacturers", ctx, prefix, limit)}
}

func (_c *mockdocumentStore_SuggestManufacturers_Call) Run(run func(ctx context.Context, prefix string, limit int)) *mockdocumentStore_SuggestManufacturers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockdocumentStore_SuggestManufacturers_Call) Return(strings []string, err error) *mockdocumentStore_SuggestManufacturers_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *mockdocumentStore_SuggestManufacturers_Call) RunAndReturn(run func(ctx context.Context, prefix string, limit int) ([]string, error)) *mockdocumentStore_SuggestManufacturers_Call {
	_c.Call.Return(run)
	return _c
}

// SuggestTags provides a mock function for the type mockdocumentStore
func (_mock *mockdocumentStore) SuggestTags(ctx context.Context, prefix string, limit int) ([]model.Tag, error) {
	ret := _mock.Called(ctx, prefix, limit)

	if len(ret) == 0 {
		panic("no return value specified for SuggestTags")
	}

	var r0 []model.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) ([]model.Tag, error)); ok {
		return returnFunc(ctx, prefix, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) []model.Tag); ok {
		r0 = returnFunc(ctx, prefix, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, prefix, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockdocumentStore_SuggestTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SuggestTags'
type mockdocumentStore_SuggestTags_Call struct {
	*mock.Call
}

// SuggestTags is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
//   - limit int
func (_e *mockdocumentStore_Expecter) SuggestTags(ctx any, prefix any, limit any) *mockdocumentStore_SuggestTags_Call {
	return &mockdocumentStore_SuggestTags_Call{Call: _e.mock.On("SuggestTags", ctx, prefix, limit)}
}

func (_c *mockdocumentStore_SuggestTags_Call) Run(run func(ctx context.Context, prefix string, limit int)) *mockdocumentStore_SuggestTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockdocumentStore_SuggestTags_Call) Return(tags []model.Tag, err error) *mockdocumentStore_SuggestTags_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *mockdocumentStore_SuggestTags_Call) RunAndReturn(run func(ctx context.Context, prefix string, limit int) ([]model.Tag, error)) *mockdocumentStore_SuggestTags_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type mockdocumentStore
func (_mock *mockdocumentStore) Upsert(doc model.Document) error {
	ret := _mock.Called(doc)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(model.Document) error); ok {
		r0 = returnFunc(doc)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockdocumentStore_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type mockdocumentStore_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - doc model.Document
func (_e *mockdocumentStore_Expecter) Upsert(doc any) *mockdocumentStore_Upsert_Call {
	return &mockdocumentStore_Upsert_Call{Call: _e.mock.On("Upsert", doc)}
}

func (_c *mockdocumentStore_Upsert_Call) Run(run func(doc model.Document)) *mockdocumentStore_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.Document
		if args[0] != nil {
			arg0 = args[0].(model.Document)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockdocumentStore_Upsert_Call) Return(err error) *mockdocumentStore_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockdocumentStore_Upsert_Call) RunAndReturn(run func(doc model.Document) error) *mockdocumentStore_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// newMockeffectStore creates a new instance of mockeffectStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockeffectStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockeffectStore {
	mock := &mockeffectStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockeffectStore is an autogenerated mock type for the effectStore type
type mockeffectStore struct {
	mock.Mock
}

type mockeffectStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockeffectStore) EXPECT() *mockeffectStore_Expecter {
	return &mockeffectStore_Expecter{mock: &_m.Mock}
}

// CreateEffect provides a mock function for the type mockeffectStore
func (_mock *mockeffectStore) CreateEffect(ctx context.Context, effect *model.Effect) error {
	ret := _mock.Called(ctx, effect)

	if len(ret) == 0 {
		panic("no return value specified for CreateEffect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Effect) error); ok {
		r0 = returnFunc(ctx, effect)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockeffectStore_CreateEffect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEffect'
type mockeffectStore_CreateEffect_Call struct {
	*mock.Call
}

// CreateEffect is a helper method to define mock.On call
//   - ctx context.Context
//   - effect *model.Effect
func (_e *mockeffectStore_Expecter) CreateEffect(ctx any, effect any) *mockeffectStore_CreateEffect_Call {
	return &mockeffectStore_CreateEffect_Call{Call: _e.mock.On("CreateEffect", ctx, effect)}
}

func (_c *mockeffectStore_CreateEffect_Call) Run(run func(ctx context.Context, effect *model.Effect)) *mockeffectStore_CreateEffect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Effect
		if args[1] != nil {
			arg1 = args[1].(*model.Effect)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockeffectStore_CreateEffect_Call) Return(err error) *mockeffectStore_CreateEffect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockeffectStore_CreateEffect_Call) RunAndReturn(run func(ctx context.Context, effect *model.Effect) error) *mockeffectStore_CreateEffect_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEffect provides a mock function for the type mockeffectStore
func (_mock *mockeffectStore) DeleteEffect(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEffect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockeffectStore_DeleteEffect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEffect'
type mockeffectStore_DeleteEffect_Call struct {
	*mock.Call
}

// DeleteEffect is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *mockeffectStore_Expecter) DeleteEffect(ctx any, id any) *mockeffectStore_DeleteEffect_Call {
	return &mockeffectStore_DeleteEffect_Call{Call: _e.mock.On("DeleteEffect", ctx, id)}
}

func (_c *mockeffectStore_DeleteEffect_Call) Run(run func(ctx context.Context, id string)) *mockeffectStore_DeleteEffect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockeffectStore_DeleteEffect_Call) Return(err error) *mockeffectStore_DeleteEffect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockeffectStore_DeleteEffect_Call) RunAndReturn(run func(ctx context.Context, id string) error) *mockeffectStore_DeleteEffect_Call {
	_c.Call.Return(run)
	return _c
}

// GetEffectByID provides a mock function for the type mockeffectStore
func (_mock *mockeffectStore) GetEffectByID(ctx context.Context, id string) (*model.Effect, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetEffectByID")
	}

	var r0 *model.Effect
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Effect, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Effect); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Effect)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockeffectStore_GetEffectByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEffectByID'
type mockeffectStore_GetEffectByID_Call struct {
	*mock.Call
}

// GetEffectByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *mockeffectStore_Expecter) GetEffectByID(ctx any, id any) *mockeffectStore_GetEffectByID_Call {
	return &mockeffectStore_GetEffectByID_Call{Call: _e.mock.On("GetEffectByID", ctx, id)}
}

func (_c *mockeffectStore_GetEffectByID_Call) Run(run func(ctx context.Context, id string)) *mockeffectStore_GetEffectByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockeffectStore_GetEffectByID_Call) Return(effect *model.Effect, err error) *mockeffectStore_GetEffectByID_Call {
	_c.Call.Return(effect, err)
	return _c
}

func (_c *mockeffectStore_GetEffectByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.Effect, error)) *mockeffectStore_GetEffectByID_Call {
	_c.Call.Return(run)
	return _c
}

// SearchEffects provides a mock function for the type mockeffectStore
func (_mock *mockeffectStore) SearchEffects(ctx context.Context, query string, skip int64, limit int64, sortField string, sortOrder string) (model.PagedEffects, error) {
	ret := _mock.Called(ctx, query, skip, limit, sortField, sortOrder)

	if len(ret) == 0 {
		panic("no return value specified for SearchEffects")
	}

	var r0 model.PagedEffects
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64, string, string) (model.PagedEffects, error)); ok {
		return returnFunc(ctx, query, skip, limit, sortField, sortOrder)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64, string, string) model.PagedEffects); ok {
		r0 = returnFunc(ctx, query, skip, limit, sortField, sortOrder)
	} else {
		r0 = ret.Get(0).(model.PagedEffects)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, int64, string, string) error); ok {
		r1 = returnFunc(ctx, query, skip, limit, sortField, sortOrder)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockeffectStore_SearchEffects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchEffects'
type mockeffectStore_SearchEffects_Call struct {
	*mock.Call
}

// SearchEffects is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - skip int64
//   - limit int64
//   - sortField string
//   - sortOrder string
func (_e *mockeffectStore_Expecter) SearchEffects(ctx any, query any, skip any, limit any, sortField any, sortOrder any) *mockeffectStore_SearchEffects_Call {
	return &mockeffectStore_SearchEffects_Call{Call: _e.mock.On("SearchEffects", ctx, query, skip, limit, sortField, sortOrder)}
}

func (_c *mockeffectStore_SearchEffects_Call) Run(run func(ctx context.Context, query string, skip int64, limit int64, sortField string, sortOrder string)) *mockeffectStore_SearchEffects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *mockeffectStore_SearchEffects_Call) Return(pagedEffects model.PagedEffects, err error) *mockeffectStore_SearchEffects_Call {
	_c.Call.Return(pagedEffects, err)
	return _c
}

func (_c *mockeffectStore_SearchEffects_Call) RunAndReturn(run func(ctx context.Context, query string, skip int64, limit int64, sortField string, sortOrder string) (model.PagedEffects, error)) *mockeffectStore_SearchEffects_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEffect provides a mock function for the type mockeffectStore
func (_mock *mockeffectStore) UpdateEffect(ctx context.Context, effect *model.Effect) error {
	ret := _mock.Called(ctx, effect)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEffect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Effect) error); ok {
		r0 = returnFunc(ctx, effect)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockeffectStore_UpdateEffect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEffect'
type mockeffectStore_UpdateEffect_Call struct {
	*mock.Call
}

// UpdateEffect is a helper method to define mock.On call
//   - ctx context.Context
//   - effect *model.Effect
func (_e *mockeffectStore_Expecter) UpdateEffect(ctx any, effect any) *mockeffectStore_UpdateEffect_Call {
	return &mockeffectStore_UpdateEffect_Call{Call: _e.mock.On("UpdateEffect", ctx, effect)}
}

func (_c *mockeffectStore_UpdateEffect_Call) Run(run func(ctx context.Context, effect *model.Effect)) *mockeffectStore_UpdateEffect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Effect
		if args[1] != nil {
			arg1 = args[1].(*model.Effect)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockeffectStore_UpdateEffect_Call) Return(err error) *mockeffectStore_UpdateEffect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockeffectStore_UpdateEffect_Call) RunAndReturn(run func(ctx context.Context, effect *model.Effect) error) *mockeffectStore_UpdateEffect_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateManufacturer provides a mock function for the type mockeffectStore
func (_mock *mockeffectStore) UpdateManufacturer(ctx context.Context, manufacturer string) error {
	ret := _mock.Called(ctx, manufacturer)

	if len(ret) == 0 {
		panic("no return value specified for UpdateManufacturer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, manufacturer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockeffectStore_UpdateManufacturer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateManufacturer'
type mockeffectStore_UpdateManufacturer_Call struct {
	*mock.Call
}

// UpdateManufacturer is a helper method to define mock.On call
//   - ctx context.Context
//   - manufacturer string
func (_e *mockeffectStore_Expecter) UpdateManufacturer(ctx any, manufacturer any) *mockeffectStore_UpdateManufacturer_Call {
	return &mockeffectStore_UpdateManufacturer_Call{Call: _e.mock.On("UpdateManufacturer", ctx, manufacturer)}
}

func (_c *mockeffectStore_UpdateManufacturer_Call) Run(run func(ctx context.Context, manufacturer string)) *mockeffectStore_UpdateManufacturer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockeffectStore_UpdateManufacturer_Call) Return(err error) *mockeffectStore_UpdateManufacturer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockeffectStore_UpdateManufacturer_Call) RunAndReturn(run func(ctx context.Context, manufacturer string) error) *mockeffectStore_UpdateManufacturer_Call {
	_c.Call.Return(run)
	return _c
}

// newMockeffectTypeStore creates a new instance of mockeffectTypeStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockeffectTypeStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockeffectTypeStore {
	mock := &mockeffectTypeStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockeffectTypeStore is an autogenerated mock type for the effectTypeStore type
type mockeffectTypeStore struct {
	mock.Mock
}

type mockeffectTypeStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockeffectTypeStore) EXPECT() *mockeffectTypeStore_Expecter {
	return &mockeffectTypeStore_Expecter{mock: &_m.Mock}
}

// GetAllEffectTypes provides a mock function for the type mockeffectTypeStore
func (_mock *mockeffectTypeStore) GetAllEffectTypes(ctx context.Context) ([]model.EffectType, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllEffectTypes")
	}

	var r0 []model.EffectType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.EffectType, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.EffectType); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.EffectType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockeffectTypeStore_GetAllEffectTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllEffectTypes'
type mockeffectTypeStore_GetAllEffectTypes_Call struct {
	*mock.Call
}

// GetAllEffectTypes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockeffectTypeStore_Expecter) GetAllEffectTypes(ctx any) *mockeffectTypeStore_GetAllEffectTypes_Call {
	return &mockeffectTypeStore_GetAllEffectTypes_Call{Call: _e.mock.On("GetAllEffectTypes", ctx)}
}

func (_c *mockeffectTypeStore_GetAllEffectTypes_Call) Run(run func(ctx context.Context)) *mockeffectTypeStore_GetAllEffectTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockeffectTypeStore_GetAllEffectTypes_Call) Return(effectTypes []model.EffectType, err error) *mockeffectTypeStore_GetAllEffectTypes_Call {
	_c.Call.Return(effectTypes, err)
	return _c
}

func (_c *mockeffectTypeStore_GetAllEffectTypes_Call) RunAndReturn(run func(ctx context.Context) ([]model.EffectType, error)) *mockeffectTypeStore_GetAllEffectTypes_Call {
	_c.Call.Return(run)
	return _c
}

// newMockuserStore creates a new instance of mockuserStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockuserStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockuserStore {
	mock := &mockuserStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockuserStore is an autogenerated mock type for the userStore type
type mockuserStore struct {
	mock.Mock
}

type mockuserStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockuserStore) EXPECT() *mockuserStore_Expecter {
	return &mockuserStore_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type mockuserStore
func (_mock *mockuserStore) CreateUser(ctx context.Context, user model.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockuserStore_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type mockuserStore_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user model.User
func (_e *mockuserStore_Expecter) CreateUser(ctx any, user any) *mockuserStore_CreateUser_Call {
	return &mockuserStore_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *mockuserStore_CreateUser_Call) Run(run func(ctx context.Context, user model.User)) *mockuserStore_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.User
		if args[1] != nil {
			arg1 = args[1].(model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserStore_CreateUser_Call) Return(err error) *mockuserStore_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockuserStore_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user model.User) error) *mockuserStore_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type mockuserStore
func (_mock *mockuserStore) GetUserByEmail(ctx context.Context, email string) (*model.User, bool) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *model.User
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.User, bool)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// mockuserStore_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type mockuserStore_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *mockuserStore_Expecter) GetUserByEmail(ctx any, email any) *mockuserStore_GetUserByEmail_Call {
	return &mockuserStore_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *mockuserStore_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *mockuserStore_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserStore_GetUserByEmail_Call) Return(user *model.User, b bool) *mockuserStore_GetUserByEmail_Call {
	_c.Call.Return(user, b)
	return _c
}

func (_c *mockuserStore_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*model.User, bool)) *mockuserStore_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type mockuserStore
func (_mock *mockuserStore) GetUserByID(ctx context.Context, userID string) (*model.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuserStore_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type mockuserStore_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *mockuserStore_Expecter) GetUserByID(ctx any, userID any) *mockuserStore_GetUserByID_Call {
	return &mockuserStore_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *mockuserStore_GetUserByID_Call) Run(run func(ctx context.Context, userID string)) *mockuserStore_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserStore_GetUserByID_Call) Return(user *model.User, err error) *mockuserStore_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockuserStore_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, userID string) (*model.User, error)) *mockuserStore_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListAllUsers provides a mock function for the type mockuserStore
func (_mock *mockuserStore) ListAllUsers(ctx context.Context) ([]model.User, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAllUsers")
	}

	var r0 []model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.User, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.User); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuserStore_ListAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllUsers'
type mockuserStore_ListAllUsers_Call struct {
	*mock.Call
}

// ListAllUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockuserStore_Expecter) ListAllUsers(ctx any) *mockuserStore_ListAllUsers_Call {
	return &mockuserStore_ListAllUsers_Call{Call: _e.mock.On("ListAllUsers", ctx)}
}

func (_c *mockuserStore_ListAllUsers_Call) Run(run func(ctx context.Context)) *mockuserStore_ListAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockuserStore_ListAllUsers_Call) Return(users []model.User, err error) *mockuserStore_ListAllUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *mockuserStore_ListAllUsers_Call) RunAndReturn(run func(ctx context.Context) ([]model.User, error)) *mockuserStore_ListAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type mockuserStore
func (_mock *mockuserStore) UpdateUser(ctx context.Context, user model.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockuserStore_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type mockuserStore_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user model.User
func (_e *mockuserStore_Expecter) UpdateUser(ctx any, user any) *mockuserStore_UpdateUser_Call {
	return &mockuserStore_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, user)}
}

func (_c *mockuserStore_UpdateUser_Call) Run(run func(ctx context.Context, user model.User)) *mockuserStore_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.User
		if args[1] != nil {
			arg1 = args[1].(model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserStore_UpdateUser_Call) Return(err error) *mockuserStore_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockuserStore_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, user model.User) error) *mockuserStore_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// newMockdocumentIndex creates a new instance of mockdocumentIndex. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdocumentIndex(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdocumentIndex {
	mock := &mockdocumentIndex{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdocumentIndex is an autogenerated mock type for the documentIndex type
type mockdocumentIndex struct {
	mock.Mock
}

type mockdocumentIndex_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdocumentIndex) EXPECT() *mockdocumentIndex_Expecter {
	return &mockdocumentIndex_Expecter{mock: &_m.Mock}
}

// Search provides a mock function for the type mockdocumentIndex
func (_mock *mockdocumentIndex) Search(query model.Query) model.PagedSearchResult {
	ret := _mock.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 model.PagedSearchResult
	if returnFunc, ok := ret.Get(0).(func(model.Query) model.PagedSearchResult); ok {
		r0 = returnFunc(query)
	} else {
		r0 = ret.Get(0).(model.PagedSearchResult)
	}
	return r0
}

// mockdocumentIndex_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type mockdocumentIndex_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - query model.Query
func (_e *mockdocumentIndex_Expecter) Search(query any) *mockdocumentIndex_Search_Call {
	return &mockdocumentIndex_Search_Call{Call: _e.mock.On("Search", query)}
}

func (_c *mockdocumentIndex_Search_Call) Run(run func(query model.Query)) *mockdocumentIndex_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.Query
		if args[0] != nil {
			arg0 = args[0].(model.Query)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockdocumentIndex_Search_Call) Return(pagedSearchResult model.PagedSearchResult) *mockdocumentIndex_Search_Call {
	_c.Call.Return(pagedSearchResult)
	return _c
}

func (_c *mockdocumentIndex_Search_Call) RunAndReturn(run func(query model.Query) model.PagedSearchResult) *mockdocumentIndex_Search_Call {
	_c.Call.Return(run)
	return _c
}

// newMockblobStore creates a new instance of mockblobStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockblobStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockblobStore {
	mock := &mockblobStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockblobStore is an autogenerated mock type for the blobStore type
type mockblobStore struct {
	mock.Mock
}

type mockblobStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockblobStore) EXPECT() *mockblobStore_Expecter {
	return &mockblobStore_Expecter{mock: &_m.Mock}
}

// DeleteByInfo provides a mock function for the type mockblobStore
func (_mock *mockblobStore) DeleteByInfo(ci *model.ContainerInfo) error {
	ret := _mock.Called(ci)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByInfo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.ContainerInfo) error); ok {
		r0 = returnFunc(ci)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockblobStore_DeleteByInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByInfo'
type mockblobStore_DeleteByInfo_Call struct {
	*mock.Call
}

// DeleteByInfo is a helper method to define mock.On call
//   - ci *model.ContainerInfo
func (_e *mockblobStore_Expecter) DeleteByInfo(ci any) *mockblobStore_DeleteByInfo_Call {
	return &mockblobStore_DeleteByInfo_Call{Call: _e.mock.On("DeleteByInfo", ci)}
}

func (_c *mockblobStore_DeleteByInfo_Call) Run(run func(ci *model.ContainerInfo)) *mockblobStore_DeleteByInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.ContainerInfo
		if args[0] != nil {
			arg0 = args[0].(*model.ContainerInfo)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockblobStore_DeleteByInfo_Call) Return(err error) *mockblobStore_DeleteByInfo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockblobStore_DeleteByInfo_Call) RunAndReturn(run func(ci *model.ContainerInfo) error) *mockblobStore_DeleteByInfo_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type mockblobStore
func (_mock *mockblobStore) Load(ci *model.ContainerInfo) ([]byte, error) {
	ret := _mock.Called(ci)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.ContainerInfo) ([]byte, error)); ok {
		return returnFunc(ci)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.ContainerInfo) []byte); ok {
		r0 = returnFunc(ci)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*model.ContainerInfo) error); ok {
		r1 = returnFunc(ci)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockblobStore_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type mockblobStore_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ci *model.ContainerInfo
func (_e *mockblobStore_Expecter) Load(ci any) *mockblobStore_Load_Call {
	return &mockblobStore_Load_Call{Call: _e.mock.On("Load", ci)}
}

func (_c *mockblobStore_Load_Call) Run(run func(ci *model.ContainerInfo)) *mockblobStore_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.ContainerInfo
		if args[0] != nil {
			arg0 = args[0].(*model.ContainerInfo)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockblobStore_Load_Call) Return(bytes []byte, err error) *mockblobStore_Load_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *mockblobStore_Load_Call) RunAndReturn(run func(ci *model.ContainerInfo) ([]byte, error)) *mockblobStore_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type mockblobStore
func (_mock *mockblobStore) Save(data []byte, mimeType string, filename string) (*model.ContainerInfo, error) {
	ret := _mock.Called(data, mimeType, filename)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *model.ContainerInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, string, string) (*model.ContainerInfo, error)); ok {
		return returnFunc(data, mimeType, filename)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, string, string) *model.ContainerInfo); ok {
		r0 = returnFunc(data, mimeType, filename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ContainerInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, string, string) error); ok {
		r1 = returnFunc(data, mimeType, filename)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockblobStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type mockblobStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - data []byte
//   - mimeType string
//   - filename string
func (_e *mockblobStore_Expecter) Save(data any, mimeType any, filename any) *mockblobStore_Save_Call {
	return &mockblobStore_Save_Call{Call: _e.mock.On("Save", data, mimeType, filename)}
}

func (_c *mockblobStore_Save_Call) Run(run func(data []byte, mimeType string, filename string)) *mockblobStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockblobStore_Save_Call) Return(containerInfo *model.ContainerInfo, err error) *mockblobStore_Save_Call {
	_c.Call.Return(containerInfo, err)
	return _c
}

func (_c *mockblobStore_Save_Call) RunAndReturn(run func(data []byte, mimeType string, filename string) (*model.ContainerInfo, error)) *mockblobStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// newMockusersService creates a new instance of mockusersService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockusersService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockusersService {
	mock := &mockusersService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockusersService is an autogenerated mock type for the usersService type
type mockusersService struct {
	mock.Mock
}

type mockusersService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockusersService) EXPECT() *mockusersService_Expecter {
	return &mockusersService_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type mockusersService
func (_mock *mockusersService) Authenticate(ctx context.Context, email string, password string) (*model.User, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.User, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.User); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockusersService_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type mockusersService_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *mockusersService_Expecter) Authenticate(ctx any, email any, password any) *mockusersService_Authenticate_Call {
	return &mockusersService_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, email, password)}
}

func (_c *mockusersService_Authenticate_Call) Run(run func(ctx context.Context, email string, password string)) *mockusersService_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockusersService_Authenticate_Call) Return(user *model.User, err error) *mockusersService_Authenticate_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockusersService_Authenticate_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (*model.User, error)) *mockusersService_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type mockusersService
func (_mock *mockusersService) Register(ctx context.Context, req users.RegisterRequest) (*model.User, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, users.RegisterRequest) (*model.User, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, users.RegisterRequest) *model.User); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, users.RegisterRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockusersService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type mockusersService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - req users.RegisterRequest
func (_e *mockusersService_Expecter) Register(ctx any, req any) *mockusersService_Register_Call {
	return &mockusersService_Register_Call{Call: _e.mock.On("Register", ctx, req)}
}

func (_c *mockusersService_Register_Call) Run(run func(ctx context.Context, req users.RegisterRequest)) *mockusersService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 users.RegisterRequest
		if args[1] != nil {
			arg1 = args[1].(users.RegisterRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockusersService_Register_Call) Return(user *model.User, err error) *mockusersService_Register_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockusersService_Register_Call) RunAndReturn(run func(ctx context.Context, req users.RegisterRequest) (*model.User, error)) *mockusersService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// newMockshareService creates a new instance of mockshareService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockshareService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockshareService {
	mock := &mockshareService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockshareService is an autogenerated mock type for the shareService type
type mockshareService struct {
	mock.Mock
}

type mockshareService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockshareService) EXPECT() *mockshareService_Expecter {
	return &mockshareService_Expecter{mock: &_m.Mock}
}

// CreateShare provides a mock function for the type mockshareService
func (_mock *mockshareService) CreateShare(ctx context.Context, share *model.Share) (string, error) {
	ret := _mock.Called(ctx, share)

	if len(ret) == 0 {
		panic("no return value specified for CreateShare")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Share) (string, error)); ok {
		return returnFunc(ctx, share)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Share) string); ok {
		r0 = returnFunc(ctx, share)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Share) error); ok {
		r1 = returnFunc(ctx, share)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockshareService_CreateShare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShare'
type mockshareService_CreateShare_Call struct {
	*mock.Call
}

// CreateShare is a helper method to define mock.On call
//   - ctx context.Context
//   - share *model.Share
func (_e *mockshareService_Expecter) CreateShare(ctx any, share any) *mockshareService_CreateShare_Call {
	return &mockshareService_CreateShare_Call{Call: _e.mock.On("CreateShare", ctx, share)}
}

func (_c *mockshareService_CreateShare_Call) Run(run func(ctx context.Context, share *model.Share)) *mockshareService_CreateShare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Share
		if args[1] != nil {
			arg1 = args[1].(*model.Share)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockshareService_CreateShare_Call) Return(s string, err error) *mockshareService_CreateShare_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockshareService_CreateShare_Call) RunAndReturn(run func(ctx context.Context, share *model.Share) (string, error)) *mockshareService_CreateShare_Call {
	_c.Call.Return(run)
	return _c
}

// GetShare provides a mock function for the type mockshareService
func (_mock *mockshareService) GetShare(ctx context.Context, link string) (*model.Share, error) {
	ret := _mock.Called(ctx, link)

	if len(ret) == 0 {
		panic("no return value specified for GetShare")
	}

	var r0 *model.Share
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Share, error)); ok {
		return returnFunc(ctx, link)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Share); ok {
		r0 = returnFunc(ctx, link)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Share)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, link)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockshareService_GetShare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShare'
type mockshareService_GetShare_Call struct {
	*mock.Call
}

// GetShare is a helper method to define mock.On call
//   - ctx context.Context
//   - link string
func (_e *mockshareService_Expecter) GetShare(ctx any, link any) *mockshareService_GetShare_Call {
	return &mockshareService_GetShare_Call{Call: _e.mock.On("GetShare", ctx, link)}
}

func (_c *mockshareService_GetShare_Call) Run(run func(ctx context.Context, link string)) *mockshareService_GetShare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockshareService_GetShare_Call) Return(share *model.Share, err error) *mockshareService_GetShare_Call {
	_c.Call.Return(share, err)
	return _c
}

func (_c *mockshareService_GetShare_Call) RunAndReturn(run func(ctx context.Context, link string) (*model.Share, error)) *mockshareService_GetShare_Call {
	_c.Call.Return(run)
	return _c
}

// newMockhasherService creates a new instance of mockhasherService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockhasherService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockhasherService {
	mock := &mockhasherService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockhasherService is an autogenerated mock type for the hasherService type
type mockhasherService struct {
	mock.Mock
}

type mockhasherService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockhasherService) EXPECT() *mockhasherService_Expecter {
	return &mockhasherService_Expecter{mock: &_m.Mock}
}

// GetHashFromPayload provides a mock function for the type mockhasherService
func (_mock *mockhasherService) GetHashFromPayload(payload []byte) string {
	ret := _mock.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for GetHashFromPayload")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func([]byte) string); ok {
		r0 = returnFunc(payload)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// mockhasherService_GetHashFromPayload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHashFromPayload'
type mockhasherService_GetHashFromPayload_Call struct {
	*mock.Call
}

// GetHashFromPayload is a helper method to define mock.On call
//   - payload []byte
func (_e *mockhasherService_Expecter) GetHashFromPayload(payload any) *mockhasherService_GetHashFromPayload_Call {
	return &mockhasherService_GetHashFromPayload_Call{Call: _e.mock.On("GetHashFromPayload", payload)}
}

func (_c *mockhasherService_GetHashFromPayload_Call) Run(run func(payload []byte)) *mockhasherService_GetHashFromPayload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockhasherService_GetHashFromPayload_Call) Return(s string) *mockhasherService_GetHashFromPayload_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *mockhasherService_GetHashFromPayload_Call) RunAndReturn(run func(payload []byte) string) *mockhasherService_GetHashFromPayload_Call {
	_c.Call.Return(run)
	return _c
}

// newMockmeasurementService creates a new instance of mockmeasurementService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockmeasurementService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockmeasurementService {
	mock := &mockmeasurementService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockmeasurementService is an autogenerated mock type for the measurementService type
type mockmeasurementService struct {
	mock.Mock
}

type mockmeasurementService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockmeasurementService) EXPECT() *mockmeasurementService_Expecter {
	return &mockmeasurementService_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type mockmeasurementService
func (_mock *mockmeasurementService) Start(name string) measurement.Monitor {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 measurement.Monitor
	if returnFunc, ok := ret.Get(0).(func(string) measurement.Monitor); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(measurement.Monitor)
		}
	}
	return r0
}

// mockmeasurementService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type mockmeasurementService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - name string
func (_e *mockmeasurementService_Expecter) Start(name any) *mockmeasurementService_Start_Call {
	return &mockmeasurementService_Start_Call{Call: _e.mock.On("Start", name)}
}

func (_c *mockmeasurementService_Start_Call) Run(run func(name string)) *mockmeasurementService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockmeasurementService_Start_Call) Return(monitor measurement.Monitor) *mockmeasurementService_Start_Call {
	_c.Call.Return(monitor)
	return _c
}

func (_c *mockmeasurementService_Start_Call) RunAndReturn(run func(name string) measurement.Monitor) *mockmeasurementService_Start_Call {
	_c.Call.Return(run)
	return _c
}
