// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package index

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/willie68/schematic2/backend/internal/domain"
)

// newMockdocStoreInterface creates a new instance of mockdocStoreInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdocStoreInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdocStoreInterface {
	mock := &mockdocStoreInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdocStoreInterface is an autogenerated mock type for the docStoreInterface type
type mockdocStoreInterface struct {
	mock.Mock
}

type mockdocStoreInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdocStoreInterface) EXPECT() *mockdocStoreInterface_Expecter {
	return &mockdocStoreInterface_Expecter{mock: &_m.Mock}
}

// Search provides a mock function for the type mockdocStoreInterface
func (_mock *mockdocStoreInterface) Search(filter domain.SearchFilter) domain.PagedSearchResult {
	ret := _mock.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 domain.PagedSearchResult
	if returnFunc, ok := ret.Get(0).(func(domain.SearchFilter) domain.PagedSearchResult); ok {
		r0 = returnFunc(filter)
	} else {
		r0 = ret.Get(0).(domain.PagedSearchResult)
	}
	return r0
}

// mockdocStoreInterface_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type mockdocStoreInterface_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - filter domain.SearchFilter
func (_e *mockdocStoreInterface_Expecter) Search(filter interface{}) *mockdocStoreInterface_Search_Call {
	return &mockdocStoreInterface_Search_Call{Call: _e.mock.On("Search", filter)}
}

func (_c *mockdocStoreInterface_Search_Call) Run(run func(filter domain.SearchFilter)) *mockdocStoreInterface_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.SearchFilter
		if args[0] != nil {
			arg0 = args[0].(domain.SearchFilter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockdocStoreInterface_Search_Call) Return(pagedSearchResult domain.PagedSearchResult) *mockdocStoreInterface_Search_Call {
	_c.Call.Return(pagedSearchResult)
	return _c
}

func (_c *mockdocStoreInterface_Search_Call) RunAndReturn(run func(filter domain.SearchFilter) domain.PagedSearchResult) *mockdocStoreInterface_Search_Call {
	_c.Call.Return(run)
	return _c
}
