// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package users

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/willie68/schematics2/backend/internal/domain/model"
)

// newMockuserStore creates a new instance of mockuserStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockuserStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockuserStore {
	mock := &mockuserStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockuserStore is an autogenerated mock type for the userStore type
type mockuserStore struct {
	mock.Mock
}

type mockuserStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockuserStore) EXPECT() *mockuserStore_Expecter {
	return &mockuserStore_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type mockuserStore
func (_mock *mockuserStore) CreateUser(ctx context.Context, user model.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockuserStore_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type mockuserStore_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user model.User
func (_e *mockuserStore_Expecter) CreateUser(ctx interface{}, user interface{}) *mockuserStore_CreateUser_Call {
	return &mockuserStore_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *mockuserStore_CreateUser_Call) Run(run func(ctx context.Context, user model.User)) *mockuserStore_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.User
		if args[1] != nil {
			arg1 = args[1].(model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserStore_CreateUser_Call) Return(err error) *mockuserStore_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockuserStore_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user model.User) error) *mockuserStore_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type mockuserStore
func (_mock *mockuserStore) GetUserByEmail(ctx context.Context, email string) (model.User, bool) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 model.User
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.User, bool)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// mockuserStore_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type mockuserStore_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *mockuserStore_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *mockuserStore_GetUserByEmail_Call {
	return &mockuserStore_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *mockuserStore_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *mockuserStore_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserStore_GetUserByEmail_Call) Return(user model.User, b bool) *mockuserStore_GetUserByEmail_Call {
	_c.Call.Return(user, b)
	return _c
}

func (_c *mockuserStore_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (model.User, bool)) *mockuserStore_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}
