// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package main_test

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// newMockshttpsrv creates a new instance of mockshttpsrv. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockshttpsrv(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockshttpsrv {
	mock := &mockshttpsrv{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockshttpsrv is an autogenerated mock type for the shttpsrv type
type mockshttpsrv struct {
	mock.Mock
}

type mockshttpsrv_Expecter struct {
	mock *mock.Mock
}

func (_m *mockshttpsrv) EXPECT() *mockshttpsrv_Expecter {
	return &mockshttpsrv_Expecter{mock: &_m.Mock}
}

// ShutdownServers provides a mock function for the type mockshttpsrv
func (_mock *mockshttpsrv) ShutdownServers() {
	_mock.Called()
	return
}

// mockshttpsrv_ShutdownServers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShutdownServers'
type mockshttpsrv_ShutdownServers_Call struct {
	*mock.Call
}

// ShutdownServers is a helper method to define mock.On call
func (_e *mockshttpsrv_Expecter) ShutdownServers() *mockshttpsrv_ShutdownServers_Call {
	return &mockshttpsrv_ShutdownServers_Call{Call: _e.mock.On("ShutdownServers")}
}

func (_c *mockshttpsrv_ShutdownServers_Call) Run(run func()) *mockshttpsrv_ShutdownServers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockshttpsrv_ShutdownServers_Call) Return() *mockshttpsrv_ShutdownServers_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockshttpsrv_ShutdownServers_Call) RunAndReturn(run func()) *mockshttpsrv_ShutdownServers_Call {
	_c.Run(run)
	return _c
}

// StartServers provides a mock function for the type mockshttpsrv
func (_mock *mockshttpsrv) StartServers(router http.Handler, healthRouter http.Handler) {
	_mock.Called(router, healthRouter)
	return
}

// mockshttpsrv_StartServers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartServers'
type mockshttpsrv_StartServers_Call struct {
	*mock.Call
}

// StartServers is a helper method to define mock.On call
//   - router http.Handler
//   - healthRouter http.Handler
func (_e *mockshttpsrv_Expecter) StartServers(router interface{}, healthRouter interface{}) *mockshttpsrv_StartServers_Call {
	return &mockshttpsrv_StartServers_Call{Call: _e.mock.On("StartServers", router, healthRouter)}
}

func (_c *mockshttpsrv_StartServers_Call) Run(run func(router http.Handler, healthRouter http.Handler)) *mockshttpsrv_StartServers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.Handler
		if args[0] != nil {
			arg0 = args[0].(http.Handler)
		}
		var arg1 http.Handler
		if args[1] != nil {
			arg1 = args[1].(http.Handler)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockshttpsrv_StartServers_Call) Return() *mockshttpsrv_StartServers_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockshttpsrv_StartServers_Call) RunAndReturn(run func(router http.Handler, healthRouter http.Handler)) *mockshttpsrv_StartServers_Call {
	_c.Run(run)
	return _c
}
