blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/willie68/schematic/discussions
    about: Allgemeine Fragen und Diskussionen
  - name: Dokumentation
    url: https://github.com/willie68/schematic#dokumentation
    about: README und BUILD.md durchschauen
