mongodb:
  username: schematics
  password: schematics


# db.createUser({user: "schematics",pwd: "schematics",roles: [{ role: "readWrite", db: "schematics" },{ role: "dbAdmin", db: "schematics" }]})