// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package health

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockCheck creates a new instance of MockCheck. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCheck(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCheck {
	mock := &MockCheck{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCheck is an autogenerated mock type for the Check type
type MockCheck struct {
	mock.Mock
}

type MockCheck_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCheck) EXPECT() *MockCheck_Expecter {
	return &MockCheck_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type MockCheck
func (_mock *MockCheck) Check() (bool, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (bool, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCheck_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockCheck_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
func (_e *MockCheck_Expecter) Check() *MockCheck_Check_Call {
	return &MockCheck_Check_Call{Call: _e.mock.On("Check")}
}

func (_c *MockCheck_Check_Call) Run(run func()) *MockCheck_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCheck_Check_Call) Return(b bool, err error) *MockCheck_Check_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockCheck_Check_Call) RunAndReturn(run func() (bool, error)) *MockCheck_Check_Call {
	_c.Call.Return(run)
	return _c
}

// CheckName provides a mock function for the type MockCheck
func (_mock *MockCheck) CheckName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CheckName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCheck_CheckName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckName'
type MockCheck_CheckName_Call struct {
	*mock.Call
}

// CheckName is a helper method to define mock.On call
func (_e *MockCheck_Expecter) CheckName() *MockCheck_CheckName_Call {
	return &MockCheck_CheckName_Call{Call: _e.mock.On("CheckName")}
}

func (_c *MockCheck_CheckName_Call) Run(run func()) *MockCheck_CheckName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCheck_CheckName_Call) Return(s string) *MockCheck_CheckName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCheck_CheckName_Call) RunAndReturn(run func() string) *MockCheck_CheckName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRegisterer creates a new instance of MockRegisterer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegisterer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegisterer {
	mock := &MockRegisterer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRegisterer is an autogenerated mock type for the Registerer type
type MockRegisterer struct {
	mock.Mock
}

type MockRegisterer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegisterer) EXPECT() *MockRegisterer_Expecter {
	return &MockRegisterer_Expecter{mock: &_m.Mock}
}

// Register provides a mock function for the type MockRegisterer
func (_mock *MockRegisterer) Register(check Check) {
	_mock.Called(check)
	return
}

// MockRegisterer_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockRegisterer_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - check Check
func (_e *MockRegisterer_Expecter) Register(check interface{}) *MockRegisterer_Register_Call {
	return &MockRegisterer_Register_Call{Call: _e.mock.On("Register", check)}
}

func (_c *MockRegisterer_Register_Call) Run(run func(check Check)) *MockRegisterer_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Check
		if args[0] != nil {
			arg0 = args[0].(Check)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegisterer_Register_Call) Return() *MockRegisterer_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRegisterer_Register_Call) RunAndReturn(run func(check Check)) *MockRegisterer_Register_Call {
	_c.Run(run)
	return _c
}

// NewMockUnregisterer creates a new instance of MockUnregisterer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnregisterer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnregisterer {
	mock := &MockUnregisterer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUnregisterer is an autogenerated mock type for the Unregisterer type
type MockUnregisterer struct {
	mock.Mock
}

type MockUnregisterer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnregisterer) EXPECT() *MockUnregisterer_Expecter {
	return &MockUnregisterer_Expecter{mock: &_m.Mock}
}

// Unregister provides a mock function for the type MockUnregisterer
func (_mock *MockUnregisterer) Unregister(checkname string) bool {
	ret := _mock.Called(checkname)

	if len(ret) == 0 {
		panic("no return value specified for Unregister")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(checkname)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockUnregisterer_Unregister_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unregister'
type MockUnregisterer_Unregister_Call struct {
	*mock.Call
}

// Unregister is a helper method to define mock.On call
//   - checkname string
func (_e *MockUnregisterer_Expecter) Unregister(checkname interface{}) *MockUnregisterer_Unregister_Call {
	return &MockUnregisterer_Unregister_Call{Call: _e.mock.On("Unregister", checkname)}
}

func (_c *MockUnregisterer_Unregister_Call) Run(run func(checkname string)) *MockUnregisterer_Unregister_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUnregisterer_Unregister_Call) Return(b bool) *MockUnregisterer_Unregister_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockUnregisterer_Unregister_Call) RunAndReturn(run func(checkname string) bool) *MockUnregisterer_Unregister_Call {
	_c.Call.Return(run)
	return _c
}
